<?php
/**
 * @file
 * Code for the Feature formation CERT feature.
 */

include_once 'feature_formation_cert.features.inc';

/**
 * Implements hook_node_view().
 */
function feature_formation_cert_node_view($node, $view_mode, $langcode) {
    //dpm($node->type);
    if ($node->type == 'formation') {
        //dpm($node);
        $block = module_invoke('webform', 'block_view', 'client-block-6');
        $settings = field_extra_fields_get_display('node',$node->type,$view_mode);
        if($settings["extra_field_form_info"]['visible']){
            $node->content["extra_field_form_info"] = array(
                "#markup" => $block['content'],
            );
        }
    }
}
/**
 * Implements hook_field_extra_fields().
 */
function feature_formation_cert_field_extra_fields() {
    $extra['node']['formation'] = array(
        'display' => array(
            'extra_field_form_info' => array(
                'label' => t('Demande infos (extra)'),
                'weight' => 0,
            ),
        )
    );

    return $extra;
}

